// <auto-generated />
using DotNetLessons.WebApi.DbModel;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DotNetLessons.WebApi.Migrations
{
    [DbContext(typeof(DotNetLessonsContext))]
    [Migration("20220623092918_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.6");

            modelBuilder.Entity("DotNetLessons.WebApi.Entities.Address", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("GalaxyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasConsmicRadiation")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PersonId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlanetName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AddressId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("DotNetLessons.WebApi.Entities.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFromEarth")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PersonId");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("DotNetLessons.WebApi.Entities.Person", b =>
                {
                    b.HasOne("DotNetLessons.WebApi.Entities.Address", "AddressNavigation")
                        .WithMany("PersonsNavigation")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AddressNavigation");
                });

            modelBuilder.Entity("DotNetLessons.WebApi.Entities.Address", b =>
                {
                    b.Navigation("PersonsNavigation");
                });
#pragma warning restore 612, 618
        }
    }
}
